version: "3.9"

services:
  web:
    build: .
    command: python /test_sellwin/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/test_sellwin
    ports:
      - 8000:8000
    depends_on:
      - migration
  migration:
    build: .
    image: app
    command: python manage.py migrate
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: