version: "3.9"

services:
  web:
    build: .
    command: python /test_sellwin/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/test_sellwin
    ports:
      - 8000:8000
    env_file:
      - envs/web.env
      - envs/db.env
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - envs/db.env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports: 
      - '5432:5432'
volumes:
  postgres_data:
