# Generated by Django 4.1.6 on 2023-02-11 22:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='discount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='cards',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cards',
            name='last_use_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cards',
            name='number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='cards',
            name='orders',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bonus_system.orders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cards',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cards',
            name='series',
            field=models.CharField(choices=[('SF', 'Staff card'), ('DF', 'Default'), ('PR', 'Prime')], default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cards',
            name='state',
            field=models.CharField(choices=[('AC', 'Activated'), ('NA', 'Not activated'), ('OD', 'Overdue')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='cards',
            name='total_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='num',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='order_discount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='orders',
            name='sell_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('discount_cost', models.IntegerField(blank=True, null=True)),
                ('order', models.ManyToManyField(to='bonus_system.orders')),
            ],
        ),
    ]
