# Generated by Django 4.1.6 on 2023-02-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_system', '0002_cards_discount_cards_end_date_cards_last_use_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cards',
            new_name='Card',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
