# Generated by Django 4.1.6 on 2023-02-16 23:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_system', '0003_alter_card_end_date_alter_card_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='all_orders',
            field=models.CharField(max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 23, 22, 54, 566391, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='card',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 23, 22, 54, 566391, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bonus_system.card', to_field='all_orders'),
        ),
    ]
