# Generated by Django 4.1.6 on 2023-02-16 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_system', '0004_card_all_orders_alter_card_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 23, 27, 11, 778122, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='card',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 23, 27, 11, 778122, tzinfo=datetime.timezone.utc)),
        ),
    ]
