# Generated by Django 4.1.6 on 2023-02-12 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_system', '0005_card_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='card',
            name='slug',
        ),
    ]
