# Generated by Django 4.1.6 on 2023-02-12 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_system', '0006_remove_card_orders_remove_card_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='bonus_system.card'),
            preserve_default=False,
        ),
    ]
