# Generated by Django 4.1.6 on 2023-02-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_system', '0007_order_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deleted',
            field=models.BooleanField(default=1, verbose_name='Was deleted'),
            preserve_default=False,
        ),
    ]
