# Generated by Django 4.1.6 on 2023-02-15 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_system', '0008_card_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'get_latest_by': 'release_date'},
        ),
        migrations.AlterField(
            model_name='order',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonus_system.card'),
        ),
    ]
