# Generated by Django 4.1.6 on 2023-02-15 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_system', '0009_alter_card_options_alter_order_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Was deleted'),
        ),
        migrations.AlterField(
            model_name='card',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 15, 21, 0, 28, 801711, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='release_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 15, 21, 0, 28, 801698, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='total_orders',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
