# Generated by Django 4.1.6 on 2023-02-20 13:53

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_system', '0012_alter_card_end_date_alter_card_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 20, 13, 53, 49, 731729, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='card',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 13, 53, 49, 731714, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 20, 13, 53, 49, 732166, tzinfo=datetime.timezone.utc), null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 2, 20, 13, 48, 49, 732124, tzinfo=datetime.timezone.utc)), django.core.validators.MaxValueValidator(datetime.datetime(2023, 2, 20, 13, 58, 49, 732153, tzinfo=datetime.timezone.utc))]),
        ),
    ]
