# Generated by Django 4.1.6 on 2023-02-22 22:23

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(choices=[('SF', 'Staff card'), ('DF', 'Default'), ('PR', 'Prime')], max_length=2)),
                ('number', models.CharField(max_length=16, unique=True)),
                ('release_date', models.DateTimeField(default=datetime.datetime(2023, 2, 22, 22, 23, 46, 878649, tzinfo=datetime.timezone.utc))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2023, 8, 22, 22, 23, 46, 878661, tzinfo=datetime.timezone.utc))),
                ('last_use_date', models.DateTimeField(blank=True, null=True)),
                ('total_orders', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('state', models.CharField(choices=[('AC', 'Activated'), ('NA', 'Not activated'), ('OD', 'Overdue')], default='NA', max_length=2)),
                ('discount', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Was deleted')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=50, unique=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 22, 22, 23, 46, 879058, tzinfo=datetime.timezone.utc), null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 2, 22, 22, 18, 46, 879011, tzinfo=datetime.timezone.utc)), django.core.validators.MaxValueValidator(datetime.datetime(2023, 2, 22, 22, 28, 46, 879043, tzinfo=datetime.timezone.utc))])),
                ('sell_price', models.FloatField(blank=True, null=True)),
                ('order_discount', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_discount', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.card', to_field='number')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_price', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.ManyToManyField(blank=True, related_name='products', to='core.order')),
            ],
        ),
    ]
