# Generated by Django 4.1.6 on 2023-02-24 09:38

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_card_end_date_alter_card_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 9, 38, 8, 618765, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='card',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 9, 38, 8, 618749, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 24, 9, 38, 8, 619136, tzinfo=datetime.timezone.utc), null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 2, 24, 9, 33, 8, 619096, tzinfo=datetime.timezone.utc)), django.core.validators.MaxValueValidator(datetime.datetime(2023, 2, 24, 9, 43, 8, 619124, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='order',
            name='num',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
